development:
  adapter: postgresql
  encoding: unicode
  database: fulfilist_dev
  pool: 5

test:
  adapter: postgresq
  encoding: unicode
  database: fulfilist_test
  pool: 5
  
production:
  adapter: postgresql
  encoding: unicode
  database: fulfilist_production
  pool: 5

